"""Make mpesa_phone_number nullable in rewards

Revision ID: 13232ed9d891
Revises: 7a092adcc50d
Create Date: 2025-07-29 12:52:11.180721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13232ed9d891'
down_revision = '7a092adcc50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'mpesa_phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'mpesa_phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
