"""add approval_status to items

Revision ID: 65c9aa3d9699
Revises: e19f6eee1c63
Create Date: 2025-07-31 11:03:16.546058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c9aa3d9699'
down_revision = 'e19f6eee1c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
