"""Make finder_user_id nullable in rewards

Revision ID: 7a092adcc50d
Revises: f8adbdb19864
Create Date: 2025-07-29 12:15:49.968391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a092adcc50d'
down_revision = 'f8adbdb19864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'finder_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'finder_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
