"""Add category field to items

Revision ID: e19f6eee1c63
Revises: 13232ed9d891
Create Date: 2025-07-29 23:14:20.731794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19f6eee1c63'
down_revision = '13232ed9d891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
