"""Increase password_hash column size to 255

Revision ID: f8adbdb19864
Revises: 06ef1aad882a
Create Date: 2025-07-29 10:39:06.203976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8adbdb19864'
down_revision = '06ef1aad882a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('reward_amount', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('reward_status', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('mpesa_phone_number', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('mpesa_transaction_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'reports', ['mpesa_transaction_id'])
    op.add_column('rewards', sa.Column('report_id', sa.Integer(), nullable=True))
    op.add_column('rewards', sa.Column('finder_user_id', sa.Integer(), nullable=False))
    op.add_column('rewards', sa.Column('owner_user_id', sa.Integer(), nullable=False))
    op.add_column('rewards', sa.Column('mpesa_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('rewards', sa.Column('mpesa_phone_number', sa.String(length=20), nullable=False))
    op.add_column('rewards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'rewards', ['mpesa_transaction_id'])
    op.drop_constraint('rewards_paid_to_id_fkey', 'rewards', type_='foreignkey')
    op.drop_constraint('rewards_offered_by_id_fkey', 'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'rewards', 'users', ['owner_user_id'], ['id'])
    op.create_foreign_key(None, 'rewards', 'users', ['finder_user_id'], ['id'])
    op.drop_column('rewards', 'offered_by_id')
    op.drop_column('rewards', 'paid_to_id')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.add_column('rewards', sa.Column('paid_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rewards', sa.Column('offered_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_foreign_key('rewards_offered_by_id_fkey', 'rewards', 'users', ['offered_by_id'], ['id'])
    op.create_foreign_key('rewards_paid_to_id_fkey', 'rewards', 'users', ['paid_to_id'], ['id'])
    op.drop_constraint(None, 'rewards', type_='unique')
    op.drop_column('rewards', 'updated_at')
    op.drop_column('rewards', 'mpesa_phone_number')
    op.drop_column('rewards', 'mpesa_transaction_id')
    op.drop_column('rewards', 'owner_user_id')
    op.drop_column('rewards', 'finder_user_id')
    op.drop_column('rewards', 'report_id')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_column('reports', 'mpesa_transaction_id')
    op.drop_column('reports', 'mpesa_phone_number')
    op.drop_column('reports', 'reward_status')
    op.drop_column('reports', 'reward_amount')
    # ### end Alembic commands ###
